### ISSUE TITLE
 UserIdleState is not defined at IdleDetectIsomorph.handleIdleChange

### ISSUE THREAD

**Issue by HyoilKim** [annexare/IdleDetect#1]
Hi :) 

I have an issue when I run this module.
`UserIdleState` is not declared in any code. but the module uses the `UserIdleState`
How can I fix this error?

![image](https://user-images.githubusercontent.com/23691938/185081585-4ca092ca-5b95-488b-8018-6fba52b0b388.png)

Thank you in advacne

**Comment by HyoilKim** [comment]
`ScreenIdleState` also does not exists

**Comment by HyoilKim** [comment]
I think `this.hanldeIdleChagne` function in `../IdleDetectIsomorph.js` should be changed.

```typescript
AS-IS
this.handleIdleChange = () => {
  ...
  if (userState === UserIdleState.idle || screenState === ScreenIdleState.locked) {
      this.handleIdle();
  }
};

TO-BE
this.handleIdleChange = () => {
  ...
  if (userState === 'idle' || screenState === 'locked') {
      this.handleIdle();
  }
};

**Comment by dmythro** [comment]
Hey @HyoilKim, could you please specify browser/version? So it's easier to reproduce and fix.

**Comment by dmythro** [comment]
Both `UserIdleState` and `ScreenIdleState` are declared globally in `src/global.d.ts`.

**Comment by HyoilKim** [comment]
> could you please specify browser/version? 

Chrome/Version 103.0.5060.53

**Comment by HyoilKim** [comment]
FYI, I got an error when I ran `npm install idle-detect`. so I ran `yarn add idle-detect`

**Comment by HyoilKim** [comment]
`yarn add idle-detect` command doesn't download `global.d.ts`. Do you know the reason?

**Comment by dmythro** [comment]
I will check builds once again. And will check if I can improve test coverage to be sure module works well everywhere.

**Comment by dmythro** [comment]
@HyoilKim thanks for info. Please check new version `0.1.2` if it works for you.
It'll try to find time for auto-tests.

**Comment by HyoilKim** [comment]
Great! It works for me.
Thank you for the quick reply and update. I'm going to close this issue
