### ISSUE TITLE
It doesn't catch `screenState` on Ubuntu

### ISSUE THREAD

**Issue by HyoilKim** [annexare/IdleDetect#2]
It doesn't run `this.handle()` when I lock my screen
```typescript
if (userState === UserIdleState.idle || screenState === ScreenIdleState.locked) {
    this.handleIdle();
}
```
OS: Ubuntu 20.04.4 LTS

Did you test it?

**Comment by HyoilKim** [comment]
@dmythro

**Comment by dmythro** [comment]
Sure, I tested it on recent macOS and Chrome at the time of publishing a module (as we used it on a project but then switched to non-isomorph version). Native API was still a draft, so probably something has changed, need to re-check everything now and add some test coverage — I'll see how to make it stable, meanwhile I'd suggest switch to non-isomorph one.

**Comment by dmythro** [comment]
Hey @HyoilKim could you debug this on Ubuntu now? Is it working after you give permissions? Chrome/Firefox. And let me know browser versions, if `'IdleDetector' in window` etc.

The `screenState` feature detection is only available when `IdleDetector` API is there (`isIdleDetectorSupported()` or `'IdleDetector' in window`).
