### ISSUE TITLE
IdleDetectIsomorph.js:39 Uncaught TypeError: (intermediate value).cleanupAndStop is not a function

### ISSUE THREAD

**Issue by HyoilKim** [annexare/IdleDetect#3]
When I block permission after 5 seconds and a timer times out, I got the error
![image](https://user-images.githubusercontent.com/23691938/186046928-2283ff99-17c4-4ab6-9559-c3e17aef4095.png)
```typescript
setTimeoutConnection = async () => { 
  this.timeout = setTimeout(
      this.onInactive,
      CONNECTION_TIMEOUT
    )
  try {
    const idleDetect = new IdleDetect(
      CONNECTION_TIMEOUT / 1000, // Unit: Second
      this.onInactive
    )
    idleDetect.start()
    if ((await window.IdleDetector.requestPermission()) === 'granted') {
      if (this.timeout) {
        clearTimeout(this.timeout)
      }
    }
  } catch {
    // Ignore errors
  }
}
```
Chrome: Version 104.0.5112.101
Ubuntu: 20.04

**Comment by HyoilKim** [comment]
@dmythro

**Comment by dmythro** [comment]
@HyoilKim hey, I've added Cypress tests and fixed couple issues. Please check it out.
Also I plan to add better builds/publishing via CI soon with next releases.
